<?php

namespace Database\Seeders;

use App\Enums\CategoryStatus;
use App\Enums\ProductStatus;
use App\Models\Category;
use App\Models\Product;
use App\Models\Tenant;
use Illuminate\Database\Seeder;
use RuntimeException;

class DemoGarmentCatalogSeeder extends Seeder
{
    private const ASSETS = [
        'mint-tshirt.png' => 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAALBUlEQVR42u3dX2hW9R/A8c9y5JWUVkQURQOJFikTZY5oBQVBjYSuQuqqLmSEEV6IqwTBngyiizSjiGBWQvQHBjMQFOEpa2KwhBoI0VVECOFqRTjY1kW4nMmYz57nOed8v6/X3Q/j1zo753ze38+eVgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVEr/xMicq+B6QJE6XAIobsjVu7d0uC6uCwgAyPBUm/Owc41AAEBWA82Ac61AAECGQyz3wea6QfE6XQIobnjR3O+HGAAbAKjU0PcjANcUBABkdsr3IUDXGQQAZDKMDCXXHYrmMwAYPGT/vRcE2ACAoe8U6vvi+4INABgw5HqvCAFSd41LgOHvlOl6iEZsAMDgB9sABAAY/CAESJGbGYO/zQwR30MoA58BwOAA9xsZ8iMAvIhhGfeebQBV5cbF4G8jw8L3FsrCjwAwIMB9SYb8CAAvWGjyPWobgAAAgx8hAAIADH6EAJSDzwBg+IP7GRsA8KIE2wAEABj8IAQQAGDwgxAgDT4DgOEPngNsAMALD2wDyIGbDYO/zbzk3SPuEcrAjwDwYgfPCxnyIwC8yKDEz45tAK3ixsLgL4CXunvGPYMNAF7igI0AbeczABj+4DkjQ0oSL6SCOMm5h9xDFMmPAPDShoo/g0KARvgRAIZ/gddwVVdv1tdxVVfvnHvJ80gxVCNeNG02PlBb8L+nfjqV7XN4aQD1jA65OZrANgABgMFf8sGfewQstv0QA0IAAYDBn/zwFwAiQAhQBJ8BwPCvwDD0z4vnGBsAvDAS3QLksglYyvB3+rcNoPX8a4AY/JDZMy4EsAHA4C/hFqBndCjJF3T/xMjcUv/5sRGg9XwGwPA3/EsYCal9X5Y6/PH8YwOABz/rLUBKm4CrGf5O/7YB2ABAspY65FLYBBj+IABQ+zS4LahqBFj7ex8gAIBlnHYvRkBVQuDi13o1w9/pH9pP9WXOZwGKP+E3MiTLeGK79F4y/J3+EQAIAJoYAWUMgUYHv+EvABAAiAAR0MDPyosOgeUMfsPf8EcAIABYxhC90iBt5Uv98nulWV8zAgABgAAQAQ1abKg28qJf7L5o1deJAEAAIAJEwDK0YsiW9evC8EcAIABEQBMHbxm+BgQAAgARIAQqyuA3/CknvwgIDE9fP9gAYAtgC2AbYPA7/ZODTpcAqjVUyxwCBj8IACCjEDD4oXqsgvgfPwaoniJiwNCvHut/bAAg0a1Aq2PA0AcbAGwBSHxDYNg7/WMDACS0IQCI8HsAcFoAzzMCAAAQADg1ODWA5xgBAAAIAABAAJAm60Pw/CIAAAABgFME4LlFAAAAAgCnCcDzigAAAAQAACAAqARrRfCcIgAAAAGA0wXg+UQAAAACAKcMwHOJAAAABAAAIACoBOtG8DwiAAAAAYBTB+A5RAAAAAIApw/A84cAAAAEAAAgAKgEa0jw3CEAAAABgNMI4HlDAAAAAgCnEsBzhgAAANqk0yWANI0P1Jr2/9UzOuSCQmKskmi6/omROVchjcEvBMrF+h8bAKCtg//yv4cQgOrzGQCcUgz/0v/98FwhAICSDGMRAAIAnFYyG/4iwPOEAAAABAA4teR2+rYF8BwhAAAAAQBOULmculPcAjh5IwCgoi/ReveWDi9xqnwPuX9pJb8ICNEBS7yn/JZLbACghAPZiZ+U7jH3MjYA4EWJjQDYAGBIO/GT+kbAfY0NAHg5YiMAAgAvWVcBIQDN4UcAlH6AW/VTxXt9Ofe7K4gNAIIBbATABoA8hroTP7luBNz32AAgDsBGAGwASHvQO/FjIyCAsQHAiR9sBMAGAMMfPA8gAAAAAQAACAAAQAAA6++5K0aG34wjhw/GyKH9cdstN0dExLmJegzvf2XBX/veG3vi3ETdRQMBAFTdwddeisGde+OxrYPx/uHPY++u7RERMT09HWu77ogVK/59BXR0dMSdt98a09PTLhoIAKDqbrphdaxceW1ERHxx7Mt494NP5v/szA9nY8O67oiIWHf32vj+7I8uGAgAIAV7Xn87jn78Try178Xo27g+vj793fyfHa+PxcP3b46IiIf6N8fx+pgLBgIASMFHnx2JTY88Gd98eyb2vfxC7Hr+2f8C4KtT8eB9myIi4oG+jXHi5GkXDAQAUHU3rrk+ejfcG5O/T8WHn47G408/F89sfWL+z89P/hGzs7PzHwyc+vMvFw0EAFB1c3MRwwdq8wN+zerr4udffl3w1xyrj8XuHduc/iFD/lsAkKjfzk/G9qFX49CBWvx94ULMzMzE4M6F/+rf0RMnY/eObdH36FMuGGTG758mC6n9x1bGB2ql+5p6RoeSumf8fn5S50cAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAABAAAIAABAAAAAAgAAEABA2/WMDvl6AAEAAAgAsAVw+gcEAAAgAMAWwOkfEAAgAgx/EACACDD8IQudLgGkFQHjAzWDHxAAIAQMfkAAQHYhAHAlPgMAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACU3z9iyFj9h19aFgAAAABJRU5ErkJggg==',
        'navy-hoodie.png' => 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAKa0lEQVR42u3csW3bahfHYSpQ5QU8QOAxPILTq/EMXkAuoi6VZ1Cj3i4ygMcwPIAXcKsUAZJIkBFIpsiX//M8XT58uJDfS/L8dOibrgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoa+YIINfXb9+3n/1nvD7ee06AAACSh70oAAEAGPiCAAQAYOALAhAAgMEvBEAAAIa+GAABABj8QgAEAGDwCwEQAEDpwS8EoA1fHAEY/s4BbAAAA882AGwAAMPf+YANAGCw2QaADQBg+Ds3sAEADDDbALABAMMf5wkCAAwrnCsIADCkcL4gAMBwwjmDAABDCecNAgAMI5w7CAAwhHD+IADA8PHvARAAYOj49wH8j79dCwoMm1P+Jr0qPydUNXcEkKWvIXjon+ObNtgAgG//xb/5OgsQAGD4Fx52zgUEABj+xYebc4Lp8F8BwIS0PtQMXbABAN/+iw9W5wYCAAz/wgPMGUKbvAKARqUMLgMYBAD45lp0aI758/i7C0AAgGHp5wIEALT3rTF9SI7189kCgAAAw18EAAIAag9FPy8IAMAw9HODAICahl4TVx+CQ//8XgOAAADfgJ0DCABg2G+Hht5452ELAAIAAAQA+Pbv278tAAgAwPB3PiAAAAABAEGGWgf7dtvWOXkNgAAAAAQAACAAIJr1f5u8BgABAAAIAPBt1rkBAgAAEABwDO9/cR0gAAAAAQD4huncINvcEcCww8wvtxn6IACg8JATAgY/CACwFZhV/vmB4fkGgm+cDakQAs4eBAAYPggBGIn/CgDDH1wn2ACABzrYBmADAIY/rh+wAQAPbmwDQACAwY8QgInyCgDDH1xn2ACABzLYBmADAIY/uP6wAQAPXrANwAYADH9wXWIDAB6wYBuAAACDHyHgGUuzvALA8AfXLzYA4MEJtgHYAIDhD65rbADAAxJsA7ABAMMfXO/YAIAHIdgGYAMAAAgA8O0f3AcIAABAAAAAAoB41p7gfkAAAAACAAA4N//9KYOz7vyc5/Vy58/XtyufJ4S/EwAbAABAAAAAAoAJs/4H9wcCAAAQAACAACCO9Sa4TxAAAIAAAAAEAHGsNcH9ggAAAAQAACAAiGOdCe4bBAAAIAAAAAFAHGtMcP8gAAAAAQAACADiWF+C+wgBAAAIAABAABDH2hLcTwgAAEAAAKd6Xi93/nx9uxr9M+1/hv3PCAgAirCuBPcVAgAAEAAAgAAgjjUluL8QAACAAAAABABxrCfBfYYAAAAEAAAgAIhjLQnuNwQAACAAAAABQBzrSHDfIQAAAAEAAAgA4lhDgvsPAQAACAAAQAAQx/oR3IcIAABAAAAAAoA41o7gfkQAAAACAAAQAMSxbgT3JQIAABAAAIAAII41I7g/EQAAgAAAAAQAcawXwX2KAAAABAAAIACIY60I7lcEAAAgAAAAAUAc60Rw3yIAAAABAAAIAOJYI4L7FwEAAAgAAEAAEMf6ENzHCAAAQAAAQ3teL3f+fH27auaz7X+W/c8KCAAmwtoQ3M8IAABAAAAAAoA41oXgvkYAAAACAAAQAMSxJgT3NwIAABAAAIAAII71ILjPEQAAgAAAAAQAcawFwf2OAAAABAAAIACIYx0I7nsEAABQwNwRQPtuFsvux0+fD7ABoCfWgNMY/sf87z4f7n8EAIQO/1aGbOufDxAAEDf8xx6yrX8+QADwAes/wHNAAAAAAgAAEADEsfYDPA8EANCgp82q1/9ftc8HCACIjYCxh2vrnw8QAPzDui8jAloZrq1/PjwXOGzmCNzoAF3Xda+P92aCDQAAIADw7d+3Glw3ng8IAABAAAAAAoBWWe8BnhMIAErw/h/XDwgAAEAA1GKtB3heIAAAQABAJu9vcR2BACjNOg/w3EAAAAACAAAEAHGs8QDPDwQAZfjFLVxPIAAAAAFQh/Ud4DmCAAAABAC5vK/FdQUCoCRrO8DzBAEAAAgAABAAxKm8rvOeFteX5woCAAAQAACAAAhlTQd4viAAKMX7f1xnIAAAAAFQg/Uc4DmDAAAABADZvJfF9QYCoCRrOcDzBgEAAAgAAEAAxLGOAzx3EACU4xeycN2BAAAABEA+azjA8wcBAAAIAPJ5D4vrDwRAOdZvgOcQAgAAEAAAgACIY+3m/SuuQ88jBAAAIAAAAAEQx7oN8FxCAFCS9664HkEAAAACIJs1G+D5hAAAAAQAACAA4liv/eYXrnBdek4hAAAAAQAACIAg1mqA5xUCgLK8Z8X1CQIAABAAuazTAM8tBAAAIACow/tVXKcgAMqwRgM8vxAAAIAAAAAEQBzrs7+8V8X16jmGAAAABAAAIABCWJsBnmcIAABAAFCLX6jCdQv9mzuCdtxttuXXZE+blQuBaDeLZc0ffLH883x7WMzEkQDA4D/8cBQCGPz5zzwhMC6vAAx/D0twPXv+FaS+XPxN6+sbgt9C5lh9vcN3nw93n2MDYPg7J3D9OicEgIvdeYHr1nkhAAAAAaBynRu4Xp2bAAAABAAAkMlfBAQDe397cQgfuLi8cgggAMDQr3xOYgDOyysAMPydG9gAAAZYe2doGwA2AGD4O09AAIBh5VwBAQAACADwLdX5AgIADCfnDAgAABAAAIAAAI5hLe28QQAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAABAAAIAABAANCrh8Vs5hScG65XnJsAAAAEgMrFeeG6dV4IABe7c3JOuH6dEwLARe98wHXsfBAALn7nAq5n58JJ5o6gnZvgbrPdOgsPBNzn7nMEgJsCcJ/DWXgFAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAEAAAgAAAAAQB86OLyyiE4bxAAAIAAAAAEAGSylnbOIADAcML5ggAAAAQA+JaKcwUBAIYVzhOGNncEcN6h9f724jAMfrABAEMM5wY2AFBumNkIGPogAMCQAxiFVwAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAEAAAgAAEAAAAACAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwPB+AeqqcLyxOdLfAAAAAElFTkSuQmCC',
        'coral-polo.png' => 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAKr0lEQVR42u3dsU5UTRiA4YOhpNOKhFCYcFPYU0lHwwXY2EFFL5dEA7EgJFTaWdhhBeJ6dvfsMmdmvpnnqf4I+i/HnfO9M6zLMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADADH7f3D0NwzD8OP781PN1eP76n68HkM87lwDyDrznYdd7BCwO/983d0+9BxHktOMSQJ5BNwzDsHd++t/Hf325GIZhGD5cX+70dk1WXY/ergkIAGho4C8aG3i9RcCq4b8YAIsEAQgACDP01w3/niJg3fCfEgFiAAQAVD3wNxn+Y4OvpQG37tsg20aAIAABAFUN/G2Gf6sRsM3w3zYCBAEIACg69LcdeK1FwFuGf4oIEAMgACDLwE8x/MeGXsQBtng9U14PQQACAKoa+qkGXvQISDn85wgAMQACAAO/yuEfOQJSD/8cESAIEABg8Fcz/CNGwFzDP3cECAEEABj8RYd/pAiYe/iXiAAhQMv8LAAM/8qH/9ifXdt75uca/nP/2TU8j8AJAAS6YecaSmO735I71LFrXfJaOA0AJwB0Ovhb362NDddSX3PJ4e85Bk4AoPgRbYmhV/okoJbhX+IUwIkATgDA8C+24y15ElDTzr/0iYPTAJwAQIc33hqOu0vvgF0HpwEIAOhqx1XT97pLDj/XQQggAKCLwV/b0Cs5/FwHIUBsXgOA4d+A3MO49Vf7e97iBADcQEMNvhw7YNfAaQBOAGC2wW/409Lfk/cPwAkABNvxRxz+c+6AXQcnAjgBgG6Gf+3DJNeQNvz7eb7jBADcCA1Bw99pAE4AIO3gtwuKESte+2At4AQAutvxtzAQX++IH+8f1n7+/uFBE19rVE4EEAAY/CIg6WCcMvxfR4DhLwRom28BYPh3MGw2Gf7bfL6/D+sGAQD/3MDcxMq7PTnL+vuwhhAAuGk1rcVdp78HawoBAG5Sho/rb40hAGD9jckQwnW33ohj1yXAjQjirj3/WgAnAGS/+Rj+dqOut7WIAMDNxlAylFxnaxMBQKs3GFfBcHJ9rVMEAHYWND4wDVxrFgGAmwiGputqDSMAcNPAsHI9rWkEAE3dKFwFQ8t1tL4RANgh0PngNICtdQQAbgYYnq6ftY8AAAwx1w0EACF5G9E2h1nq/1/0x4/1jwAAAAQAdgF2ta6TdY8AAAw31wcEAHYDRBxyc/35UR831jsCAAAQANDuKYDrAQgAJnMsGH/oRTymN/ytcwQAiABfPyAAsDsArG8EANgF+7oBAYBdgmFYZqBGeqxY1wgAsCP2dQICAAD65kiIpfys8DL2zk+T7qof7x9Gf/3o6uvLf9+enI1+zv7hQbbHyXwc/zNm1yWAuvz6crHVcJ3q9eBf/LVlIZDq6wLq4VsA2DVUGgG+HqxjBAAw2+5/k48DAgC7ByrZNZfaXdf++LB+EQDQfAR4/IAAABGw1LoX+aV8EaDhDwKA4Bwj2mEb8tYt7fHPACHIoE/1TwOfd/lT3gdAGEC7FCKTeWOg8hYjYMqgXfZGQFOseiOgtzwm7P4pz7cAINhJgMcHCADsKsSAx4F1igAAg9/jAgQAiADDHxAApOB4EaxPBAAAIACwywCsSwQAACAAsNsArEcEAAAgAAAAAUAIjh3BOkQAAAACALsPwPpDAAAAAgC7EMC6QwAAAAIAABAAhOA4Eqw3BAAAUDkVSVI/jj8/uQp1ebx/GP31o6uvL/99e3I2+jn7hwcuoN0/jdp1CaAvrwf/4q8tCwGgPb4FgN0JWF8IAKC33f8mHwcEAAAgAOAvx5RgXSEAgIqse5GfFwGCAAC7FbCeaJh/BgidngJMeR8AoF2qkll5Y6Dylr0R0BTeCMjun3b5FgAACACwgwLPGwQABL6Jfri+3HETJ/JzyPOXOXkRIKIDJj6nvKYFAQAb3jxz3DgN/ra9/3bxfdnHfn46/dhaCHg+IwDAjdLgn/g5LYYAzMVrAAg7pH2P3/B/6+fX+hz0vEYAgMFv+Gf6fZ6TCAAw+Ak6/EtGgOcoAgBW3BzdVMk1vEtFwFufs57r5OJFgDQXDFDbc9iLBXECgBvihKFux2/3X+ufN/eJgOc9TgAQB+BEAJwA0Pagt+OnxzUwtg5cGZwAYMcPTgTACQCGP1gPIAAAAAEAAAgAIKzUP8wn1w8HAgEAAAgAgFK7drt/EABAZxFg+IMAADqLAMMfBADQWQQY/jCddwKExu0fHgyP9w9b/b6aImDVD/Yx+EEAAAkioJbhb8jDfHwLADqKgKjDH3ACAGSIAMAJAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEMkfsNHkX8CRRMMAAAAASUVORK5CYII=',
    ];

    public function run(): void
    {
        $tenant = Tenant::query()->where('domain', env('DEMO_TENANT_DOMAIN', 'demo.smartmirror.local'))->first();

        if (! $tenant) {
            return;
        }

        $this->writeAssets();

        $tops = Category::query()->updateOrCreate(
            ['tenant_id' => $tenant->id, 'slug' => 'tops'],
            ['name' => 'T-Shirts & Tops', 'status' => CategoryStatus::Active]
        );

        $products = [
            [
                'sku' => 'TSHIRT-001',
                'name' => 'Mint Smart Mirror T-Shirt',
                'description' => 'Transparent PNG demo T-shirt prepared for real-time AR fitting tests.',
                'unit_price' => 799,
                'asset' => 'mint-tshirt.png',
                'sizes' => [
                    ['size_label' => 'S', 'shoulder_width_cm' => 42, 'chest_width_cm' => 48, 'height_cm' => 66, 'sort_order' => 0],
                    ['size_label' => 'M', 'shoulder_width_cm' => 44, 'chest_width_cm' => 51, 'height_cm' => 69, 'sort_order' => 1],
                    ['size_label' => 'L', 'shoulder_width_cm' => 46, 'chest_width_cm' => 54, 'height_cm' => 72, 'sort_order' => 2],
                ],
            ],
            [
                'sku' => 'HOODIE-001',
                'name' => 'Navy Smart Mirror Hoodie',
                'description' => 'Transparent PNG hoodie with long sleeves for pose and overlay testing.',
                'unit_price' => 1299,
                'asset' => 'navy-hoodie.png',
                'sizes' => [
                    ['size_label' => 'M', 'shoulder_width_cm' => 45, 'chest_width_cm' => 55, 'height_cm' => 70, 'sort_order' => 0],
                    ['size_label' => 'L', 'shoulder_width_cm' => 47, 'chest_width_cm' => 58, 'height_cm' => 73, 'sort_order' => 1],
                    ['size_label' => 'XL', 'shoulder_width_cm' => 49, 'chest_width_cm' => 61, 'height_cm' => 76, 'sort_order' => 2],
                ],
            ],
            [
                'sku' => 'POLO-001',
                'name' => 'Coral Smart Mirror Polo',
                'description' => 'Transparent PNG polo shirt for switching between catalog garments.',
                'unit_price' => 949,
                'asset' => 'coral-polo.png',
                'sizes' => [
                    ['size_label' => 'S', 'shoulder_width_cm' => 41, 'chest_width_cm' => 47, 'height_cm' => 65, 'sort_order' => 0],
                    ['size_label' => 'M', 'shoulder_width_cm' => 43, 'chest_width_cm' => 50, 'height_cm' => 68, 'sort_order' => 1],
                    ['size_label' => 'L', 'shoulder_width_cm' => 45, 'chest_width_cm' => 53, 'height_cm' => 71, 'sort_order' => 2],
                ],
            ],
        ];

        foreach ($products as $item) {
            $product = Product::withTrashed()->firstOrNew([
                'tenant_id' => $tenant->id,
                'sku' => $item['sku'],
            ]);

            if ($product->trashed()) {
                $product->restore();
            }

            $assetUrl = '/demo-garments/'.$item['asset'];

            $product->fill([
                'category_id' => $tops->id,
                'name' => $item['name'],
                'description' => $item['description'],
                'base_image_url' => $assetUrl,
                'texture_image_url' => $assetUrl,
                'unit_price' => $item['unit_price'],
                'currency' => 'EGP',
                'status' => ProductStatus::Active,
            ])->save();

            $labels = [];

            foreach ($item['sizes'] as $size) {
                $labels[] = $size['size_label'];
                $product->sizingCharts()->updateOrCreate(
                    ['size_label' => $size['size_label']],
                    $size
                );
            }

            $product->sizingCharts()->whereNotIn('size_label', $labels)->delete();
        }
    }

    private function writeAssets(): void
    {
        $directory = public_path('demo-garments');

        if (! is_dir($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
            throw new RuntimeException('Unable to create the demo garment asset directory.');
        }

        foreach (self::ASSETS as $filename => $encoded) {
            $bytes = base64_decode($encoded, true);

            if ($bytes === false) {
                throw new RuntimeException('Unable to decode demo garment asset: '.$filename);
            }

            if (file_put_contents($directory.'/'.$filename, $bytes) === false) {
                throw new RuntimeException('Unable to write demo garment asset: '.$filename);
            }
        }
    }
}
