<?php

return [
    'experience_mode' => env('KIOSK_EXPERIENCE_MODE', 'hybrid'),
    'ai_tryon_enabled' => (bool) env('KIOSK_AI_TRYON_ENABLED', true),
    'ai_available' => true,
    'privacy_notice_mode' => env('KIOSK_PRIVACY_NOTICE_MODE', 'off'),
    'privacy_notice_ar' => env('KIOSK_PRIVACY_NOTICE_AR', 'تُستخدم الكاميرا لتجربة الملابس، وتُحذف الصور تلقائيًا خلال 24 ساعة'),
    'privacy_notice_en' => env('KIOSK_PRIVACY_NOTICE_EN', 'Camera images are used for virtual try-on and deleted automatically within 24 hours.'),
    'outfit_count' => (int) env('KIOSK_OUTFIT_COUNT', 3),
    'auto_start_delay_seconds' => (float) env('KIOSK_AUTO_START_DELAY_SECONDS', 1.0),
    'countdown_seconds' => (float) env('KIOSK_COUNTDOWN_SECONDS', 0.9),
    'capture_burst_count' => (int) env('KIOSK_CAPTURE_BURST_COUNT', 5),
    'capture_duration_seconds' => (float) env('KIOSK_CAPTURE_DURATION_SECONDS', 2.0),
    'gallery_timeout_seconds' => (float) env('KIOSK_GALLERY_TIMEOUT_SECONDS', 45),
    'poll_interval_seconds' => (float) env('KIOSK_POLL_INTERVAL_SECONDS', 2.5),
    'pose_every_n' => (int) env('KIOSK_POSE_EVERY_N', 3),
    'hand_every_n' => (int) env('KIOSK_HAND_EVERY_N', 3),
    'kiosk_health_hud' => (bool) env('KIOSK_HEALTH_HUD', true),
    'live_restyle_enabled' => (bool) env('KIOSK_LIVE_RESTYLE_ENABLED', false),
    'sizing_mode' => env('KIOSK_SIZING_MODE', 'depth'),
    'fit_confidence_threshold' => (int) env('KIOSK_FIT_CONFIDENCE_THRESHOLD', 75),
    'max_live_yaw_deg' => (float) env('KIOSK_MAX_LIVE_YAW_DEG', 25),
    'depth_required' => (bool) env('KIOSK_DEPTH_REQUIRED', true),
    'gestures' => [
        'cooldown_seconds' => (float) env('KIOSK_GESTURE_COOLDOWN_SECONDS', 1.1),
        'hold_seconds' => (float) env('KIOSK_GESTURE_HOLD_SECONDS', 0.75),
        'swipe_distance' => (float) env('KIOSK_GESTURE_SWIPE_DISTANCE', 0.20),
    ],
];
