from __future__ import annotations

import argparse
from pathlib import Path

from smart_mirror.app_v2 import SmartMirrorAppV2
from smart_mirror.camera import scan_cameras


def parser() -> argparse.ArgumentParser:
    base = Path(__file__).resolve().parent
    p = argparse.ArgumentParser(description="AR Smart Mirror using OpenCV and MediaPipe Pose/Hands.")
    p.add_argument("--api-url", help="Laravel deployment base URL")
    p.add_argument("--pairing-code", help="One-time pairing code generated by the admin dashboard")
    p.add_argument("--device-name", default="Smart Mirror Client")
    p.add_argument("--texture", help="Local transparent garment PNG/WebP for standalone mode")
    p.add_argument("--model", default=str(base / "models" / "pose_landmarker_lite.task"))
    p.add_argument("--data-dir", default=str(base / ".smart-mirror"))
    p.add_argument("--snapshot-dir", default=str(base / ".smart-mirror" / "snapshots"))
    p.add_argument("--camera", type=int, default=0)
    p.add_argument("--camera-backend", choices=["auto", "dshow", "msmf", "any"], default="auto")
    p.add_argument("--scan-cameras", action="store_true")
    p.add_argument("--scan-max-camera", type=int, default=5)
    p.add_argument("--width", type=int, default=1280)
    p.add_argument("--height", type=int, default=720)
    p.add_argument("--reference-shoulder-cm", type=float, default=44.0)
    p.add_argument("--garment-scale", type=float, default=1.85)
    p.add_argument("--smoothing", type=float, default=0.32)
    p.add_argument("--mirror-view", action=argparse.BooleanOptionalAction, default=True)
    p.add_argument("--gestures", action=argparse.BooleanOptionalAction, default=True)
    p.add_argument("--gesture-debug", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--gesture-cooldown", type=float, default=1.10)
    p.add_argument("--gesture-hold", type=float, default=0.75)
    p.add_argument("--swipe-distance", type=float, default=0.20)
    return p


if __name__ == "__main__":
    args = parser().parse_args()
    if args.scan_cameras:
        cameras = scan_cameras(args.scan_max_camera, args.width, args.height, args.camera_backend)
        if cameras:
            for camera in cameras:
                print(
                    f"camera={camera.index} backend={camera.backend} "
                    f"resolution={camera.width}x{camera.height}"
                )
        else:
            print("No cameras opened. Check Windows camera privacy permissions and close apps using the camera.")
        raise SystemExit(0)

    SmartMirrorAppV2(args).run()
