from __future__ import annotations

import argparse
from pathlib import Path

from smart_mirror.app import SmartMirrorApp


def parser() -> argparse.ArgumentParser:
    base = Path(__file__).resolve().parent
    p = argparse.ArgumentParser(description="AR Smart Mirror using OpenCV and MediaPipe Pose/Hands.")
    p.add_argument("--api-url", help="Laravel deployment base URL")
    p.add_argument("--pairing-code", help="One-time pairing code generated by the admin dashboard")
    p.add_argument("--device-name", default="Smart Mirror Client")
    p.add_argument("--texture", help="Local transparent garment PNG/WebP for standalone mode")
    p.add_argument("--model", default=str(base / "models" / "pose_landmarker_lite.task"))
    p.add_argument("--data-dir", default=str(base / ".smart-mirror"))
    p.add_argument("--snapshot-dir", default=str(base / ".smart-mirror" / "snapshots"))
    p.add_argument("--camera", type=int, default=0)
    p.add_argument("--width", type=int, default=1280)
    p.add_argument("--height", type=int, default=720)
    p.add_argument("--reference-shoulder-cm", type=float, default=44.0)
    p.add_argument("--garment-scale", type=float, default=1.85)
    p.add_argument("--smoothing", type=float, default=0.32)
    p.add_argument("--mirror-view", action=argparse.BooleanOptionalAction, default=True)
    p.add_argument("--gestures", action=argparse.BooleanOptionalAction, default=True)
    p.add_argument("--gesture-debug", action=argparse.BooleanOptionalAction, default=False)
    p.add_argument("--gesture-cooldown", type=float, default=1.10)
    p.add_argument("--gesture-hold", type=float, default=0.75)
    p.add_argument("--swipe-distance", type=float, default=0.20)
    return p


if __name__ == "__main__":
    SmartMirrorApp(parser().parse_args()).run()
